import = ["/Users/mfpr/.config/alacritty/themes/themes/alabaster_dark.toml"]
# import = ["/Users/mfpr/.config/alacritty/themes/themes/gruvbox_light.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 10

[font.offset]
x = 0 
y = 1


[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "Full" 
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0 
y = 0 
